# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/Users/matthiasbegot/piscineW@C/W-ADS-250-LYN-3-1-systeme-matthias.begot/user_api/migrations"
