version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lavieestbelle!44
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"
    env_file:
      - ./user_api/.env
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./user_api
    container_name: user_api_app
    depends_on:
      - db
    env_file:
      - ./user_api/.env
    environment:
      MYSQL_ROOT_PASSWORD: Lavieestbelle!44
      DATABASE_URL: "mysql://root:Lavieestbelle!44@db:3306/user_db"
      RUST_LOG: debug
      RUST_BACKTRACE: full
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  mysql_data:
